---
- name: "Deploy application"
  hosts: app
  vars:
    deploy_user: appuser

  tasks:
    - name: "Actual code of  application"
      git:
        repo: 'https://github.com/Artemmkin/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: restart puma.service

    - name: Installs gems using a Gemfile
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
    - name: restart puma.service
      become: yes
      systemd:
        name: puma.service
        state: restarted
