---
- name: Configure mongodb
  hosts: db
  tags: db-tag
  become: yes
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod.service

  handlers:
    - name: restart mongod.service
      systemd:
        name: mongod.service
        state: restarted

- name: "Configure  application"
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.0.44
  tasks:
    - name: Copy systemd unit for puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: 
      - systemd daemon-reload
      - reload puma.service

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd:
        name: puma.service
        enabled: yes

  handlers:
    - name: systemd daemon-reload
      systemd:
        daemon_reload: yes

    - name: reload puma.service
      systemd:
        name: puma.service
        state: reloaded

- name: "Deploy application"
  hosts: app
  tags: deploy-tag
  tasks:
    - name: "Actual code of  application"
      git:
        repo: 'https://github.com/Artemmkin/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma.service

    - name: Installs gems using a Gemfile
      bundler:
        state: present
        chdir: /home/appuser/reddit

  handlers:
    - name: restart puma.service
      become: yes
      systemd:
        name: puma.service
        state: restarted



