---
- name: "Configure hosts & deploy application"
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.42

  tasks:
    - name: Change mongo config file
      become: yes
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod.service

    - name: Copy systemd unit for puma
      become: yes
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: 
      - systemd daemon-reload
      - reload puma.service
      tags: app-tag

    - name: "Actual code of  application"
      git:
        repo: 'https://github.com/Artemmkin/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: restart puma.service


    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag
      notify: restart puma.service

    - name: Installs gems using a Gemfile
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag

    - name: enable and started puma
      become: yes
      systemd:
        name: puma.service
        state: started
        enabled: yes
      tags: deploy-tag
 
  handlers:
    - name: restart mongod.service
      become: yes
      systemd:
        name: mongod.service
        state: restarted

    - name: systemd daemon-reload
      become: yes
      systemd:
        daemon_reload: yes

    - name: restart puma.service
      become: yes
      systemd:
        name: puma.service
        state: restarted

    - name: reload puma.service
      become: yes
      systemd:
        name: puma.service
        state: reloaded



